### ISSUE TITLE
Set a Static Proxy Port

### ISSUE THREAD

**Issue by dullahan8** [Bunnyspa/GFChipCalc#1]
I downloaded and started poking around this app recently.

I noticed that every time I open the app and click the proxy server icon, the port is different. Sometimes it's 8080, sometimes it's 49526, sometimes it's something else.
![javaw_2021-03-30_14-53-42](https://user-images.githubusercontent.com/7637030/113062788-25667f80-9169-11eb-8e19-92bbe14140c0.jpg)
![javaw_2021-03-30_15-04-07](https://user-images.githubusercontent.com/7637030/113062794-2697ac80-9169-11eb-8a5f-93b2ac346911.jpg)

I use Bluestacks as my Android emulator, updating the proxy address every time I want to use GFChipCalc means I need to close Bluestacks, run a command in CMD to update the proxy settings, and relaunch the game. It's quite inconvenient.

Is there a way to tell GFChipCalc to use a specific port each time? (just like how GFLAlarm does it)

**Comment by TheDukeofErl** [comment]
@dullahan8 If you're already using GFAlarm, it might be worth considering setting that up to output a json file that can be fed into GFChipCalc instead. In GFAlarm, go to Settings->File Save and check "Save Equip Info." You can find that output file in <gf_alarm_root>/Info/ and feed it into GFChipCalc via the "Open Inventory" button.

**Comment by dullahan8** [comment]
Oh very cool. This makes things easy thanks!
