### ISSUE TITLE
CHIP gfci and gfcc files are exported in a way that they can't be read again in version 8.1.0

### ISSUE THREAD

**Issue by Nz-Music** [Bunnyspa/GFChipCalc#7]
**Describe the bug**
When saving/exporting either gfci or gfcc files in Version 8.1.0 of chip-cal. Part of the file when opened in a text editor shows the words orange and blue. Files new files are unreadable in version 8.1.0 and need to be altered in a text editor to be readable.

**To Reproduce**
1. Save either an gfci or gfcc file
2. Click on open (either from inventory or from hoc presets)
3. Scroll down to file you want to open (either gfci or gfcc file)
4. file will fail to load and an error file will open in the save folder version 8.1.0 of the chip-cal executable jar file is in. 

**Expected behavior**
Files instead of failing to load should open normally in previous version of chip cal. 

**Screenshots**
![image](https://user-images.githubusercontent.com/97873484/149725405-26b2c469-df45-453d-a7d0-68c6b8f8cf5b.png) Picture of Error file
![image](https://user-images.githubusercontent.com/97873484/149725578-0be286fd-1a75-42b5-9d05-e894ae94d4aa.png) Picture of what gfcc file looks like from chip-cal prior-to 8.1.0
![image](https://user-images.githubusercontent.com/97873484/149725768-886e9190-3aad-47c0-a447-b4bbb29009a3.png) Picture of what gfcc file looks like from chip-cal 8.1.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 97.0.4692.71

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS15.2
 - Browser: Google
 - Version: 194.0

**Additional context**
Contact me for any addition info. I will try my best to help;
Discord: Nz-Music#4306
Twitter: @NZMusic6
Reddit: u/Nz-Music

**Comment by bunnyspa** [comment]
Issue fixed in v8.1.1 629e1fc80ddb4b78ed44ead531687b403ba754a9
